services:
  postgres_service:
    image: postgres:15
    container_name: postgres_flight_bookings
    environment:
      POSTGRES_DB: db_flight_bookings
      POSTGRES_USER: admin
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot_app:
    build: .
    container_name: flight-bookings
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_service:5432/db_flight_bookings
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres_service

volumes:
  postgres_data: