name: Build, Initialize Seats

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-initialize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build API
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

      - name: Run Integration Tests
        run: mvn verify


