name: Build and Deploy Docker Image to Docker Hub

on:
  push:
    branches:
      - dev
      - testingDev

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: db_flight-bookings
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar JDK 21 para Maven
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'  # Otras opciones son 'zulu', 'adopt' o 'oraclejdk'

      # Imprimir la versión de Java para confirmar
      - name: Check Java version
        run: java -version

    # Imprimir el directorio de trabajo para depurar
      - name: Print working directory
        run: pwd
      - name: Check MySQL connection
        run: |
          attempt=0
          until mysql -h 127.0.0.1 -P 3306 -uroot -e "SHOW DATABASES"; do
            attempt=$((attempt+1))
            if [ $attempt -ge 10 ]; then
              echo "MySQL failed to start after 10 attempts, exiting..."
              exit 1
            fi
            echo "Waiting for MySQL... attempt $attempt"
            sleep 5
          done
      # Compilar el proyecto y generar el archivo JAR
      - name: Build JAR with Maven
        run: mvn clean install

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Verificar si el JAR existe
      - name: Verify JAR file existence
        run: |
          if [ ! -f target/flight-bookings-0.0.1-SNAPSHOT.jar ]; then
            echo "JAR file not found! Ensure 'mvn clean install' has run successfully."
            exit 1
          else
            echo "JAR file found. Proceeding with Docker build."
          fi

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flight-bookings:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flight-bookings:latest
