name: Generate and Publish Documentation

on:
  push:
    branches:
      - dev
      - testingDev

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: List apidocs folder content
        run: ls -R ./target/site/apidocs


      - name: Move Javadoc to docs folder
        run: |
          mkdir -p docs
          cp -r ./target/site/apidocs/* ./docs/

      - name: List docs folder content after copy
        run: ls -R ./docs

      - name: Disable Jekyll
        run: touch docs/.nojekyll

      - name: List docs folder content
        run: ls -R ./docs

      - name: Check permissions of target and docs folders
        run: ls -ld ./target ./docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs


